apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  name: frigate-noauth
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: &host frigate-api.eviljungle.com
    http:
      paths:
      - path: /.*/api/events
        pathType: Prefix
        backend:
          service:
            name: frigate
            port:
              number: 80
  tls:
  - hosts:
    - *host
