---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./frigate.yaml
  - ./frigate-noauth-ingress.yaml
  - ./volsync.yaml
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./config.yml
generatorOptions:
  disableNameSuffixHash: true