---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-gcp-sa
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-gcp-sa-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home-assistant
      property: home-assistant-4d8d1f2ca10f.json 
