---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        CAMERA_AUTH: "{{ .CAMERA_AUTH }}"
        HASS_TOKEN: "{{ .HASS_TOKEN }}"
        HASS_POSTGRES_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.default.svc.cluster.local/home_assistant"
        LATITUDE: "{{ .LATITUDE }}"
        LONGITUDE: "{{ .LONGITUDE }}"
        WORK_LATITUDE: "{{ .WORK_LATITUDE }}"
        WORK_LONGITUDE: "{{ .WORK_LONGITUDE }}"
        SSC_LATITUDE: "{{ .SSC_LATITUDE }}"
        SSC_LONGITUDE: "{{ .SSC_LONGITUDE }}"
        JENS_WORK_LATITUDE: "{{ .JENS_WORK_LATITUDE }}"
        JENS_WORK_LONGITUDE: "{{ .JENS_WORK_LONGITUDE }}"
        ALARMCD: "{{ .ALARMCD }}"
        SECURE_DEVICES_PIN: "{{ .SECURE_DEVICES_PIN }}"
        JEFF_WATCH_IRK: "{{ .JEFF_WATCH_IRK }}"
        JEFF_PHONE_IRK: "{{ .JEFF_PHONE_IRK }}"
        JEN_WATCH_IRK: "{{ .JEN_WATCH_IRK }}"
        JEN_PHONE_IRK: "{{ .JEN_PHONE_IRK }}"
        ANSLEY_WATCH_IRK: "{{ .ANSLEY_WATCH_IRK }}"
        ANSLEY_PHONE_IRK: "{{ .ANSLEY_PHONE_IRK }}"
        BRINLEY_PHONE_IRK: "{{ .BRINLEY_PHONE_IRK }}"
        OPNSENSE_USER: "{{ .OPNSENSE_USER }}"
        OPNSENSE_KEY: "{{ .OPNSENSE_KEY }}"
        # Postgres Init
        POSTGRES_DB: home_assistant
        POSTGRES_HOST: postgres-rw.default.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: cloudnative-pg
