---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2023.2.3
    init-db:
      image: ghcr.io/onedr0p/postgres-initdb:14.7
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: home-assistant-secret
    env:
      TZ: "America/New_York"
    envFrom:
      - secretRef:
          name: home-assistant-secret
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.0.6.56
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: hass.eviljungle.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "hass.eviljungle.com"
    prometheus:
      serviceMonitor:
        enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: "10Gi"
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.9.1
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        env:
          HASS_SERVER: http://localhost:8123
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
          hosts:
          - host: hass-vscode.eviljungle.com
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - hass-vscode.eviljungle.com
        volumeMounts:
        - name: config
          mountPath: /config
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      limits:
        memory: 3000Mi
      requests:
        cpu: 100m
        memory: 1000Mi
