---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invidious-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        INVIDIOUS_CONFIG: |
          database_url: postgres://{{ .INVIDIOUS_POSTGRES_PASS }}:{{ .INVIDIOUS_POSTGRES_USER }}@postgres-v15-rw.default.svc.cluster.local.:5432/invidious
          check_tables: true
          domain: invidious.eviljungle.com
          https_only: false
          hmac_key: {{ .HMAC_KEY }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: invidious
        INIT_POSTGRES_HOST: postgres-v15-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .INVIDIOUS_POSTGRES_PASS }}"
        INIT_POSTGRES_PASS: "{{ .INVIDIOUS_POSTGRES_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"  
  dataFrom:
    - extract:
        key: invidious
    - extract:
        key: cloudnative-pg
