---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: invidious-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/auricom/postgres-init
              tag: 15.6@sha256:e5dfcf4d53d4dfe3bf996ba02fec5145e0c4f0a3d5f14a0f529e1f8830157d20
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: invidious-secret
        containers:
          main:
            image:
              repository: quay.io/invidious/invidious
              tag: latest@sha256:ed76a9c4d976dc4ed2575b6b59a108b0cbe9e642cb581df04fd0b0321eebaa3a
            envFrom: *envFrom
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: 'nginx-tailscale'
        hosts:
          - host: "i.t.eviljungle.com"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "i.t.eviljungle.com"
