---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: audiobookshelf-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: audiobookshelf-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}:audiobookshelf'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .APPLICATION_KEY }}'
  dataFrom:
    - extract:
        key: b2
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: audiobookshelf
  namespace: default
spec:
  sourcePVC: audiobookshelf-config
  trigger:
    schedule: "0 6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: audiobookshelf-restic-secret
    cacheCapacity: 19Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: rook-ceph-block
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    retain:
      daily: 10
      within: 3d
