---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: trivy
  namespace: flux-system
spec:
  type: oci
  interval: 2h
  url: oci://ghcr.io/aquasecurity/helm-charts/trivy-operator
