---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: volsync
  path: "./default/sonarr"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sonarr
      namespace: default
  interval: 10m
  retryInterval: 1m
  timeout: 3m
