---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .AUTH0_GRAFANA_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .AUTH0_GRAFANA_CLIENT_SECRET }}"
        GF_SECURITY_ADMIN_USER: "{{ .GRAFANA_ADMIN_EMAIL }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        TESLAMATE_DB_PASSWORD: "{{ .TESLAMATE_DB_PASSWORD }}" # from teslamate
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: teslamate