---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
spec:
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        # admin_password, user_2_password
        key: cloudflare
