---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraria
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: terraria-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TERRARIA_PASS: "{{ .TERRARIA_PASS }}"
  dataFrom:
    - extract:
        key: terraria
