---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terraria
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: jacobsmile/terraria1.4
      tag: latest
      pullPolicy: Always

    env:
      TZ: "America/New_York"
      TERRARIA_WORLDSEED: "gamechanger"
      TERRARIA_WORLDS: "/config/worlds"
      TERRARIA_USECONFIGFILE: "no"

    service:
      main:
        ports:
          http:
            port: 7777
        type: LoadBalancer
        loadBalancerIP: 10.0.6.58

    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 5Gi
        mountPath: /config

    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      # limits:
      #   memory: 500Mi
