---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terraria
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: jacobsmile/terraria1.4
      tag: latest
      pullPolicy: Always

    env:
      TZ: "America/New_York"
      TERRARIA_WORLDSEED: "gamechanger"
      TERRARIA_USECONFIGFILE: "no"
      TERRARIA_MOTD: "Welcome to the eviljungle terraria vanilla (no mods) server!"

    envFrom:
      - secretRef:
          name: terraria-secret

    service:
      main:
        ports:
          http:
            port: 7777
        type: LoadBalancer
        loadBalancerIP: 10.0.6.58

    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 5Gi
        mountPath: /root/.local/share/Terraria/Worlds

    resources:
      requests:
        memory: 1Gi
        cpu: 150m
      limits:
        memory: 4Gi

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
        spec:
          initialDelaySeconds: 360
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraria-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: terraria-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/terraria'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .MINIO_ACCESS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '{{ .MINIO_SECRET_KEY }}'
  dataFrom:
    - extract:
        key: minio
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: terraria
  namespace: default
spec:
  sourcePVC: terraria-config
  trigger:
    schedule: "0 6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: terraria-restic-secret
    cacheCapacity: 10Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: rook-ceph-block
    retain:
      daily: 10
      within: 3d
