---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.14.4
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true
    prometheus:
      namespace: monitoring
      serviceAccount: kube-prometheus-stack-prometheus
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      tolerations:
      - key: "arm"
        operator: "Exists"
    speaker:
      tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "armhf"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
