---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero
  namespace: velero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: velero-helm-values
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          credentials:
            secretContents:
              cloud: |
                [default]
                aws_access_key_id = $MINIO_ACCESS_KEY
                aws_secret_access_key = $MINIO_SECRET_KEY
  dataFrom:
    - extract:
        key: minio
