
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 3.1.2
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://truenas.home:9000
          publicUrl: https://minio.eviljungle.com
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 6h
      credentials:
        name: velero-secret
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.6.0@sha256:04b19ab31ab2c1bc56de1b18dcfc268bdfce32b0edf313869781ded2320beed0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    # enableHelmHooks: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    snapshotsEnabled: true
    deployNodeAgent: true
    upgradeCRDs: false
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
          cpu: null
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: "120h"
      mcbr-minecraft-bedrock-hourly:
        schedule: "0 */6 * * *"
        template:
          labelSelector:
            matchLabels:
              app: mcbr-minecraft-bedrock
          ttl: "120h"
          includedNamespaces:
          - default
      mcsv-minecraft-hourly:
        schedule: "0 * * * *"
        template:
          labelSelector:
            matchLabels:
              app: mcsv-minecraft
          ttl: "120h"
          includedNamespaces:
          - default
      mcsv2-minecraft-hourly:
        schedule: "0 * * * *"
        template:
          labelSelector:
            matchLabels:
              app: mcsv2-minecraft
          ttl: "120h"
          includedNamespaces:
            - default
      mc-minecraft-hourly:
        schedule: "0 */6 * * *"
        template:
          labelSelector:
            matchLabels:
              app: mc-minecraft
          ttl: "120h"
          includedNamespaces:
          - default
