---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kube-prometheus-stack-helm-values
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          alertmanager:
            config:
              global:
                slack_api_url: "{{ .DISCORD_ALERTMANAGER_WEBHOOK_URL }}"
              receivers:
              - name: 'pagerduty'
                pagerduty_configs:
                  - service_key: "{{ .PD_TOKEN }}"
          prometheus:
            prometheusSpec:
              additionalScrapeConfigs:
              - job_name: 'home-assistant'
                scrape_interval: 60s
                metrics_path: '/api/prometheus'
                authorization:
                  credentials: "{{ .PROM_HASS_TOKEN }}"
                scheme: http
                static_configs:
                - targets:
                  - home-assistant.default.svc:8123
  dataFrom:
    - extract:
        key: prometheus
