---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://raw.githubusercontent.com/1Password/connect-helm-charts/main
      chart: connect
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
      interval: 5m
  values:
    namespace: kube-system
    connect:
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
    operator:
      create: true
      autoRestart: true
      token:
        name: onepassword-token
        key: token
    serviceType: ClusterIP
