---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - proxmox-b.home:9100
        - proxmox-c.home:9100
        - opnsense.home:9100
        - nas-lan.home:9001
