---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: upsc-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
      - proxmox-b.home:8081
      - proxmox-c.home:8081
