---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: maintainerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/jorenn92/maintainerr
      tag: 2.0.2

    env:
      TZ: "America/New_York"

    service:
      main:
        ports:
          http:
            port: 6246

    ingress:
      main:
        enabled: true
        ingressClassName: nginx-tailscale
        hosts:
          - host: &host maintainerr.eviljungle.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 1Gi
        mountPath: /opt/data

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001

    resources:
      requests:
        memory: 128Mi
        cpu: 5m
      limits:
        memory: 500Mi
