---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: minio
