---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    objstoreConfig:
      type: s3
      config:
        insecure: true
    query:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: thanos.eviljungle.com
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.eviljungle.com/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.eviljungle.com/oauth2/start
        tls: true
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
    compactor:
      enabled: true
      extraFlags: ["--compact.concurrency", "4"]
      retentionResolutionRaw: 7d
      retentionResolution5m: 14d
      retentionResolution1h: 30d
      persistence:
        enabled: false
    storegateway:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      persistence:
        enabled: true
        size: 40Gi
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  valuesFrom:
  - targetPath: objstoreConfig.config.bucket
    kind: ConfigMap
    name: thanos-bucket
    valuesKey: BUCKET_NAME
  - targetPath: objstoreConfig.config.endpoint
    kind: ConfigMap
    name: thanos-bucket
    valuesKey: BUCKET_HOST
  - targetPath: objstoreConfig.config.region
    kind: ConfigMap
    name: thanos-bucket
    valuesKey: BUCKET_REGION
  - targetPath: objstoreConfig.config.access_key
    kind: Secret
    name: thanos-bucket
    valuesKey: AWS_ACCESS_KEY_ID
  - targetPath: objstoreConfig.config.secret_key
    kind: Secret
    name: thanos-bucket
    valuesKey: AWS_SECRET_ACCESS_KEY