---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.13.1
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.4.0"
    replicaCount: 2
    tolerations:
      - key: "arm"
        operator: "Exists"
    ingress:
      enabled: true
      path: /oauth2
      hosts: [auth.eviljungle.com]
      tls:
      - hosts:
        - auth.eviljungle.com
    extraArgs:
      provider: oidc
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: .eviljungle.com
      whitelist-domain: .eviljungle.com
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - oauth2-proxy
          topologyKey: "kubernetes.io/hostname"
  valuesFrom:
  - targetPath: config.clientID
    kind: Secret
    name: oauth2-proxy-secret
    valuesKey: PASSAGE_CLIENT_ID
  - targetPath: config.clientSecret
    kind: Secret
    name: oauth2-proxy-secret
    valuesKey: PASSAGE_API_KEY
  - targetPath: extraArgs.oidc-issuer-url
    kind: Secret
    name: oauth2-proxy-secret
    valuesKey: PASSAGE_ISSUER_URL
  # - targetPath: config.azureTenant
  #   kind: Secret
  #   name: oauth2-proxy-secret
  #   valuesKey: AZURE_TENANT_ID
  - targetPath: config.cookieSecret
    kind: Secret
    name: oauth2-proxy-secret
    valuesKey: OAUTH2_PROXY_COOKIE_SECRET
