---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flood-qb
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flood-qb-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: flood
