---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velocity
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: itzg/bungeecord
      tag: 2024.6.0
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: "velocity-configmap"
    minecraftProxy:
      type: velocity
      plugins:
        - https://cdn.modrinth.com/data/YnhEXQW8/versions/zh0iSh9V/slashserver-1.0-SNAPSHOT.jar
        - https://cdn.modrinth.com/data/Q10irTG0/versions/bjW4bFt7/Velocitab-1.6.6.jar
      serviceType: LoadBalancer
      loadBalancerIP: 10.0.6.107
      externalTrafficPolicy: Cluster
      configFilePath: /server/velocity.toml
    extraVolumes:
      - volumeMounts:
        - name: velocity-config
          mountPath: /config/velocity.toml
          subPath: velocity.toml
          readOnly: false
        volumes:
          - name: velocity-config
            configMap:
              name: velocity-configmap
              defaultMode: 420
              items:
                - key: velocity.toml
                  path: velocity.toml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velocity-configmap
  namespace: default
data:
  velocity.toml: |
    bind = "0.0.0.0:25577"
    player-info-forwarding-mode = "legacy"

    [servers]
    lobby = "mc-lobby-minecraft:25565"
    creative = "mc-minecraft:25565"
    survival = "mcsv-minecraft:25565"
    survival2 = "mcsv2-minecraft:25565"

    # In what order we should try servers when a player logs in or is kicked from a server.
    try = [
        "lobby"
    ]

    [forced-hosts]
    # Configure your forced hosts here.
    "mc-lobby-minecraft" = [
        "lobby"
    ]
    "mc-minecraft" = [
        "creative"
    ]
    "mcsv-minecraft" = [
        "survival"
    ]
    "mcsv2-minecraft" = [
        "survival2"
    ]
