---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcsv
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 4.18.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2024.5.0
    strategyType: Recreate
    persistence:
      storageClass: "rook-ceph-block"
      dataDir:
        enabled: true
        Size: 10Gi
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    resources:
      requests:
        memory: 9Gi
        cpu: 500m
      limits:
        memory: 9Gi
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "mcsv.eviljungle.com"
    extraEnv:
      ENABLE_AUTOPAUSE: FALSE
    minecraftServer:
      spigetResources:
        - 28140
        - 74354
        - 102931
      modUrls:
        - https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
        - https://cdn.modrinth.com/data/Lu3KuzdV/versions/w3P6ufP1/CoreProtect-22.2.jar
      eula: true
      version: "LATEST"
      type: PAPER
      forceReDownload: true
      jvmOpts: "-Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      memory: 8192M
      difficulty: normal
      spawnProtection: 0
      maxTickTime: -1
      serviceType: LoadBalancer
      gameMode: survival
      pvp: false
      onlineMode: false
      maxWorldSize: 5999968
      #worldSaveName: 'trails-20230610-13'
      worldSaveName: "walker20231022"
      levelSeed: "walker20231022"
      motd: "mcsv.eviljungle.com\n\u00A76\u00A7lSMPl\u00A7r\u00A7l - \u00A7r\u00A7c\u00A7lSMP\u00A7r\n"
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-23.png
      loadBalancerIP: 10.0.6.102
      rcon:
        enabled: false
        port: 25575
        password: "mc-rcon"
        serviceType: LoadBalancer
      extraPorts:
        # - name: map
        #   containerPort: 8123
        #   service:
        #     enabled: true
        #     type: ClusterIP
        #     port: 8123
        #   ingress:
        #     enabled: true
        #     ingressClassName: nginx-tailscale
        #     # annotations:
        #     #   nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
        #     hosts:
        #       - name: mcsv-map.t.eviljungle.com
        #         path: /
        #     tls:
        #     - hosts:
        #       - mcsv-map.t.eviljungle.com
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcsv-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mcsv-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/mcsv'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .MINIO_ACCESS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '{{ .MINIO_SECRET_KEY }}'
  dataFrom:
    - extract:
        key: minio
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mcsv
  namespace: default
spec:
  sourcePVC: mcsv-minecraft-datadir
  trigger:
    schedule: "0 6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: mcsv-restic-secret
    cacheCapacity: 20Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: rook-ceph-block
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 10
      within: 3d
