---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc
  namespace: default
spec:
  suspend: true
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 4.15.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2024.4.0-java17
    strategyType: Recreate
    persistence:
      storageClass: "rook-ceph-block"
      dataDir:
        enabled: true
        Size: 15Gi
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    resources:
      requests:
        memory: 6Gi
        cpu: 250m
      limits:
        memory: 7Gi
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      ENABLE_AUTOPAUSE: FALSE
    minecraftServer:
      modUrls:
        - https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
      spigetResources:
        - 102931
      eula: true
      version: "LATEST"
      type: PAPER
      forceReDownload: true
      jvmOpts: "-Xms6G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      memory: 6144M
      difficulty: normal
      maxTickTime: -1
      serviceType: LoadBalancer
      gameMode: creative
      onlineMode: false
      maxWorldSize: 5999968
      worldSaveName: 'world-20160823'
      motd: "\u00a7feviljungle\u00a7 - \u00a7a\u00a7lcreative\u00a7"
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-13.png
      loadBalancerIP: 10.0.6.101
      rcon:
        enabled: false
        port: 25575
        password: "mc-rcon"
        serviceType: LoadBalancer
      # extraPorts:
      #   - name: map
      #     containerPort: 8123
      #     service:
      #       enabled: true
      #       type: ClusterIP
      #       port: 8123
      #     ingress:
      #       enabled: true
      #       ingressClassName: nginx-tailscale
      #       # annotations:
      #       #   nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
      #       hosts:
      #         - name: mc-map.t.eviljungle.com
      #           path: /
      #       tls:
      #       - hosts:
      #         - mc-map.t.eviljungle.com
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mc-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mc-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/mc'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .MINIO_ACCESS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '{{ .MINIO_SECRET_KEY }}'
  dataFrom:
    - extract:
        key: minio
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mc
  namespace: default
spec:
  sourcePVC: mc-minecraft-datadir
  trigger:
    schedule: "0 6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: mc-restic-secret
    cacheCapacity: 30Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: rook-ceph-block
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 10
      within: 3d
