---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: waterfall
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft-proxy
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: itzg/bungeecord
      tag: 2022.4.1
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    resources:
      requests:
        memory: 250Mi
        cpu: 50m
      limits:
        memory: 500Mi
    tolerations:
    - key: "arm"
      operator: "Exists"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "waterfall-minecraft-proxy-config"
    extraEnv:
      #SPIGET_PLUGINS: "78915,75"
      PLUGINS: "https://cdn.modrinth.com/data/axTqSWQA/versions/tj8xmw88/Advanced-Portals-0.9.2.jar,"
    minecraftProxy:
      type: VELOCITY
      velocityVersion: latest
      # A list of .jar URLs to download into the plugins folder.
      # plugins: []
      serviceType: LoadBalancer
      loadBalancerIP: 10.0.6.106
      externalTrafficPolicy: Local
      # This can be set to the contents of your config file (only works with yaml currently)
      configFilePath: /server/velocity.toml
      config: |-
        config-version = "1.0"
        bind = "0.0.0.0:25577"
        motd = "&3eviljungle &6&Llobby"
        show-max-players = 500
        player-info-forwarding-mode: "modern"
        [servers]
        # Configure your servers here. Each key represents the server's name, and the value
        # represents the IP address of the server to connect to.
        lobby = "mc-lobby-minecraft:25565"
        creative = "mc-minecraft:25565"
        survival = "mcsv-minecraft:25565"
        survival2 = "mcsv2-minecraft:25565"
        # In what order we should try servers when a player logs in or is kicked from a server.
        try = [
          "lobby"
        ]

