---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amcrest2mqtt
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: dchesterton/amcrest2mqtt
      tag: 1.0.16

    env:
      TZ: "America/New_York"
      MQTT_HOST: emqx
      MQTT_PORT: 1883
      HOME_ASSISTANT: "true"
      MQTT_USERNAME: "mqtt"
      AMCREST_HOST: 10.4.0.11
      AMCREST_USERNAME: "admin"

    envFrom:
      - secretRef:
          name: amcrest2mqtt-secrets

    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false

    resources:
      requests:
        cpu: 15m
        memory: 64M
