---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uptimerobot
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: uptimerobot-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: uptimerobot
