---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptimerobot-prometheus
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: billimek/prometheus-uptimerobot-exporter
      tag: 0.0.1
    tolerations:
    - key: "arm"
      operator: "Exists"
    metrics:
      enabled: true
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9705
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            path: /metrics
            interval: 3m
            scrapeTimeout: 1m
  valuesFrom:
  - targetPath: uptimerobotApiKey
    kind: Secret
    name: uptimerobot-secret
    valuesKey: UPTIMEROBOT_API_KEY
