---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: botkube
      version: v0.18.0
      sourceRef:
        kind: HelmRepository
        name: botkube-charts
        namespace: flux-system
      interval: 5m
  values:
    settings:
      clusterName: k8s
      configWatcher: true
    existingCommunicationsSecretName: botkube-secret
    serviceMonitor:
      enabled: true
    sources:
      crds:
        displayName: CRDS
        kubernetes:
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
          resources:
            - name: helm.toolkit.fluxcd.io/v2beta1/helmreleases
            - name: source.toolkit.fluxcd.io/v1beta2/helmcharts
            - name: kustomize.toolkit.fluxcd.io/v1beta2/kustomizations
            - name: notification.toolkit.fluxcd.io/v1beta1/alerts
            - name: monitoring.coreos.com/v1/podmonitors
            - name: monitoring.coreos.com/v1/servicemonitors
      k8s-events:
        kubernetes:
          resources:
            - type: v1/pods
              events:
                - create
                - delete
                - error
              namespaces:
                exclude:
                  - rook-ceph
                  - kube-system
            - type: v1/services
              events:
                - create
                - delete
                - error
            - type: apps/v1/deployments
              event:
                types:
                  - create
                  - update
                  - delete
                  - error
              updateSetting:
                includeDiff: true
                fields:
                  - spec.template.spec.containers[*].image
                  - status.availableReplicas
            - type: apps/v1/statefulsets
              event:
                types:
                  - create
                  - update
                  - delete
                  - error
              updateSetting:
                includeDiff: true
                fields:
                  - spec.template.spec.containers[*].image
                  - status.readyReplicas
            - type: networking.k8s.io/v1/ingresses
              event:
                types:
                  - create
                  - delete
                  - error
            - type: v1/nodes
              event:
                types:
                  - create
                  - delete
                  - error
            - type: v1/namespaces
              event:
                types:
                  - create
                  - delete
                  - error
            - type: v1/persistentvolumes
              event:
                types:
                  - create
                  - delete
                  - error
            - type: v1/persistentvolumeclaims
              event:
                types:
                  - create
                  - delete
                  - error
            - type: v1/configmaps
              event:
                types:
                  - create
                  - delete
                  - error
            - type: apps/v1/daemonsets
              event:
                types:
                  - create
                  - delete
                  - error
              updateSetting:
                includeDiff: true
                fields:
                  - spec.template.spec.containers[*].image
                  - status.numberReady
            - type: batch/v1/jobs
              event:
                types:
                  - create
                  - update
                  - delete
                  - error
              updateSetting:
                includeDiff: true
                fields:
                  - spec.template.spec.containers[*].image
                  - status.conditions[*].type
