---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botkube
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: botkube-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: botkube
