---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: botkube
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: botkube-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        comm_config.yaml: |
          communications:
            'default-group':
              discord:
                enabled: true
                token: '{{ .BOTKUBE_DISCORD_TOKEN }}'
                botID: '{{ .BOTKUBE_DISCORD_BOT_ID }}'
                ## Format: channels.{alias}
                channels:
                  'default':
                    id: '{{ .BOTKUBE_DISCORD_CHANNEL_ID }}'
                    notification:
                      # -- If true, the notifications are not sent to the channel. They can be enabled with `@Botkube` command anytime.
                      disabled: false
                    bindings:
                      # -- Executors configuration for a given channel.
                      executors:
                        - kubectl-read-only
                        - helm
                      # -- Notification sources configuration for a given channel.
                      sources:
                        - k8s-events
                        - crds
                notification:
                  # -- Configures notification type that are sent. Possible values: `short`, `long`.
                  type: short
  dataFrom:
    - extract:
        key: botkube
