---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.32.0.6973-a787c5a8e

    env:
      TZ: "America/New_York"
      PLEX_UID: "1000"
      PLEX_GID: "1000"
    envFrom:
      - secretRef:
          name: plex-secret

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.0.6.53
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: "plex.eviljungle.com"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.eviljungle.com"

    podSecurityContext:
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [44, 109, 10000]

    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 35Gi
      transcode:
        enabled: false
        existingClaim: nfs-media-pvc
        subPath: Videos/transcode/
        readOnly: false
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
      nfs-media-pvc:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: /data
        readOnly: false

    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 500m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 5000Mi
