---
name: "HelmRelease Diff"

on:
  pull_request:
    branches: ["master"]
    paths: ["**.yaml"]

env:
  KUBERNETES_DIR: ./

jobs:
  changed-files:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@5d2fcdb4cbef720a52f49fd05d8c7edd18a64758 # v36.0.15
        with:
          json: true
          files: |
            **/*.yaml
          files_ignore: |
            .github/**
            flux-system/**
            Taskfile.yml

      - id: set-matrix
        run: echo "matrix={\"file\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "${GITHUB_OUTPUT}"

  diff:
    name: Diff on Helm Releases
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Checkout default branch
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default_branch

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Tools
        run: |
          brew install helm homeport/tap/dyff kustomize yq

      - name: Diff
        id: diff
        run: |
          diff=$(npx zx ./.github/scripts/helmReleaseDiff.mjs \
            --current-release "default_branch/${{ matrix.file }}" \
            --incoming-release "${{ matrix.file }}" \
            --kubernetes-dir ${{ env.KUBERNETES_DIR }} \
            --diff-tool "diff")
          echo "diff<<EOF" >> "${GITHUB_OUTPUT}"
          echo "${diff}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Find Comment
        if: ${{ always() && steps.diff.outputs.diff != '' }}
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "Helm Release Diff: ${{ matrix.file }}"

      - name: Create or update comment
        if: ${{ always() && steps.diff.outputs.diff != '' }}
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b # v3.0.1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Helm Release Diff: `${{ matrix.file }}`

            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
          edit-mode: replace

      - name: Dyff
        id: dyff
        run: |
          diff=$(npx zx ./.github/scripts/helmReleaseDiff.mjs \
            --current-release "default_branch/${{ matrix.file }}" \
            --incoming-release "${{ matrix.file }}" \
            --kubernetes-dir ${{ env.KUBERNETES_DIR }} \
            --diff-tool "dyff")
          echo "diff<<EOF" >> "${GITHUB_OUTPUT}"
          echo "${diff}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Find Comment
        if: ${{ always() && steps.dyff.outputs.diff != '' }}
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
        id: find-comment-dyff
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "Helm Release Dyff: ${{ matrix.file }}"

      - name: Create or update comment
        if: ${{ always() && steps.dyff.outputs.diff != '' }}
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b # v3.0.1
        with:
          comment-id: ${{ steps.find-comment-dyff.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Helm Release Dyff: `${{ matrix.file }}`

            ```
            ${{ steps.dyff.outputs.diff }}
            ```
          edit-mode: replace
