name: Flux Diff
on:
  pull_request:
    branches:
      - master
    paths:
      - "**.yaml"
jobs:
  diffs:
    name: Compute diffs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_path:
          - flux-system
        resource:
          - helmrelease
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.2.3
      - name: flux-local diff
        uses: allenporter/flux-local/action/diff@4.3.1
        id: diff
        with:
          path: ${{ matrix.cluster_path }}
          resource: ${{ matrix.resource }}
          live-branch: master
      - name: PR Comments
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          message-id: ${{ github.event.pull_request.number }}/${{ matrix.cluster_path }}/${{ matrix.resource }}
          message-failure: Unable to post diff
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```