---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Flux Diff"

on:
  pull_request:
    branches: ["master"]
    paths: ["**.yaml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  diffs:
    name: Compute diffs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.2.3
      - name: flux-local diff
        uses: allenporter/flux-local/action/diff@4.3.1
        id: diff
        with:
          live-branch: master
          path: ./
          resource: helmrelease
      - name: PR Comments
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          message-id: ${{ github.event.pull_request.number }}/helmrelease
          message-failure: Unable to post diff
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
