---
name: "HelmRelease Diff"

on:
  pull_request:
    branches: ["master"]
    paths: ["**.yaml"]

env:
  KUBERNETES_DIR: ./

jobs:
  changed-files:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@7f2aa19bdcf4a00195671e368091a1e32a694ac5 # v35.5.2
        with:
          json: true
          files: |
            **/*.yaml
          files_ignore: |
            .github/**
            flux-system/**
            Taskfile.yml

      - id: set-matrix
        run: echo "matrix={\"file\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "${GITHUB_OUTPUT}"

  diff:
    name: Diff on Helm Releases
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Checkout default branch
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default_branch

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Tools
        run: |
          brew install helm homeport/tap/dyff kustomize yq

      - name: Diff
        id: diff
        run: |
          diff=$(npx zx ./.github/scripts/helmReleaseDiff.mjs \
            --current-release "default_branch/${{ matrix.file }}" \
            --incoming-release "${{ matrix.file }}" \
            --kubernetes-dir ${{ env.KUBERNETES_DIR }}) \
            --diff-tool "diff"
          echo "diff<<EOF" >> "${GITHUB_OUTPUT}"
          echo "${diff}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Find Comment
        if: ${{ always() && steps.diff.outputs.diff != '' }}
        uses: peter-evans/find-comment@85a676a52594b4481e0532825a2d8906ef96dac2 # v2.2.1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: ${{ matrix.file }}

      - name: Create or update comment
        if: ${{ always() && steps.diff.outputs.diff != '' }}
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d # v2.1.1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Helm Release: `${{ matrix.file }}`

            ```
            ${{ steps.diff.outputs.diff }}
            ```
          edit-mode: replace

      - name: Dyff
        id: dyff
        run: |
          diff=$(npx zx ./.github/scripts/helmReleaseDiff.mjs \
            --current-release "default_branch/${{ matrix.file }}" \
            --incoming-release "${{ matrix.file }}" \
            --kubernetes-dir ${{ env.KUBERNETES_DIR }}) \
            --diff-tool "dyff"
          echo "diff<<EOF" >> "${GITHUB_OUTPUT}"
          echo "${diff}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"

      - name: Find Comment
        if: ${{ always() && steps.dyff.outputs.diff != '' }}
        uses: peter-evans/find-comment@85a676a52594b4481e0532825a2d8906ef96dac2 # v2.2.1
        id: find-comment-dyff
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: ${{ matrix.file }}

      - name: Create or update comment
        if: ${{ always() && steps.dyff.outputs.diff != '' }}
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d # v2.1.1
        with:
          comment-id: ${{ steps.find-comment-dyff.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Helm Release: `${{ matrix.file }}`

            ```
            ${{ steps.dyff.outputs.diff }}
            ```
          edit-mode: replace
